<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpmn">
  <eClassifiers xsi:type="ecore:EClass" name="Exclusive" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventBased" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusive" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connections"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="#//Connections"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFlow" eSuperTypes="#//Connections"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Connections"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveBasedEvent" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Complex" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelEventBased" eSuperTypes="#//Gateway"/>
</ecore:EPackage>
